repos:
  - repo: local
    hooks:
      - id: basedpyright
        name: typecheck (basedpyright)
        entry: basedpyright
        language: system
        pass_filenames: false
        types: [python]
