# Main configuration file for training.
defaults:
  - dataloader: default
  - datamodule: default
  - model: default
  - optimizer: default
  - lr_scheduler: default
  - paths: local      # override with paths=jz on Jean-Zay
  - setup: local      # override with setup=jz_<hw> on Jean-Zay
  - experiment: ???   # must be specified at launch
  - _self_

submitit: true  # Set to false to run locally
